export type Lang = "ar" | "en";

export const productSlugs = [
  "steel-pipes",
  "aluminium-sheets",
  "copper-rods",
  "structural-beams",
] as const;

export type ProductSlug = (typeof productSlugs)[number];

export const content = {
  ar: {
    dir: "rtl" as const,
    brand: "توب ترست للمنتجات المعدنية",
    brandShort: "توب ترست",
    tagline: "مبني على الثقة",
    nav: {
      home: "الرئيسية",
      products: "المنتجات",
      services: "الخدمات",
      about: "من نحن",
      contact: "تواصل معنا",
    },
    common: {
      viewDetails: "تفاصيل المنتج",
      backToProducts: "العودة للمنتجات",
      specs: "المواصفات الفنية",
      uses: "مجالات الاستخدام",
      relatedProducts: "منتجات أخرى",
      viewAll: "عرض الكل",
      requestProduct: "اطلب عرض سعر لهذا المنتج",
    },
    hero: {
      eyebrow: "منذ 1998 · مصنع في مصر · نصدّر إلى المملكة العربية السعودية والخليج",
      title: "معادن تُصنع لتدوم",
      titleAccent: "مبني على الثقة",
      body: "مصنع مصري متخصص في توريد وتصنيع السبائك والمنتجات المعدنية، يصدّر إلى المملكة العربية السعودية ودول الخليج للمشاريع الإنشائية والصناعية والنفطية، بجودة مطابقة للمواصفات العالمية وسرعة في التسليم.",
      cta: "اطلب عرض سعر",
      cta2: "تصفح المنتجات",
    },
    stats: [
      { value: "+25", label: "سنة خبرة" },
      { value: "+1200", label: "مشروع منجز" },
      { value: "+40", label: "سبيكة ودرجة معدنية" },
      { value: "24/7", label: "دعم لوجستي" },
    ],
    productsSection: {
      eyebrow: "المنتجات",
      title: "محفظة كاملة من المعادن للصناعة والإنشاءات",
      body: "تصفح فئاتنا الرئيسية — من أنابيب الصلب وألواح الألمنيوم إلى قضبان النحاس والقطاعات الإنشائية.",
      note: "جميع المنتجات متوفرة بمواصفات متعددة وبكميات صناعية مع شهادات جودة.",
    },
    products: [
      {
        slug: "steel-pipes",
        name: "أنابيب ومواسير الصلب",
        categoryEn: "Steel Pipes",
        spec: "قطر 6 مم – 1200 مم",
        desc: "أنابيب صلب كربوني ومقاوم للصدأ للأنظمة الصناعية وخطوط النقل.",
        long: "نوفّر أنابيب الصلب الكربوني والمقاوم للصدأ الملحومة وغير الملحومة بمقاسات وسماكات متعددة، مع إمكانية القص والتسنين والطلاء الخارجي حسب متطلبات المشروع. جميع الشحنات مرفقة بشهادات تحليل كيميائي واختبارات ضغط.",
        items: [
          "ASTM A106 / A53 — صلب كربوني",
          "SS 304 / SS 316 — مقاوم للصدأ",
          "مجلفن بالغمس الساخن",
          "مطلي إيبوكسي للخطوط",
          "قص وتسنين حسب الطلب",
          "اختبارات ضغط معتمدة",
        ],
        specs: [
          { k: "القطر", v: "6 مم – 1200 مم" },
          { k: "السماكة", v: "1.5 مم – 40 مم" },
          { k: "الدرجات", v: "ASTM A106 / A53 / SS 304 / SS 316" },
          { k: "الأطوال", v: "6 م · 12 م أو حسب الطلب" },
          { k: "التشطيب", v: "أسود · مجلفن · مطلي إيبوكسي" },
        ],
        uses: ["خطوط النفط والغاز", "أنظمة الإطفاء والتكييف", "الهياكل الإنشائية", "شبكات المياه"],
      },
      {
        slug: "aluminium-sheets",
        name: "ألواح وصفائح الألمنيوم",
        categoryEn: "Aluminium Sheets",
        spec: "سماكة 0.5 مم – 60 مم",
        desc: "صفائح مدرفلة على البارد والساخن بأسطح مصقولة أو مخشنة.",
        long: "ألواح ألمنيوم بدرجات صناعية متعددة، مدرفلة على البارد أو الساخن، متوفرة بأسطح مصقولة أو مخشنة أو مؤكسدة. نقدم خدمة القص بالمقاس والثني والأنودة بألوان مختلفة.",
        items: [
          "1050 · 3003 · 5083 · 6061",
          "مدرفلة على البارد والساخن",
          "سطح طبيعي · أنودة · دهان",
          "قص بالمقاس ±0.1 مم",
          "ثني وتشكيل CNC",
          "ألواح للواجهات والصناعة",
        ],
        specs: [
          { k: "السماكة", v: "0.5 مم – 60 مم" },
          { k: "المقاسات", v: "1000×2000 · 1250×2500 · 1500×3000 مم" },
          { k: "السبائك", v: "1050 · 3003 · 5083 · 6061" },
          { k: "التشطيب", v: "طبيعي · أنودة · دهان إلكتروستاتيكي" },
          { k: "التحمل", v: "±0.1 مم" },
        ],
        uses: ["واجهات المباني", "صناعة المقطورات", "لوحات التحكم", "المعدات الغذائية"],
      },
      {
        slug: "copper-rods",
        name: "قضبان النحاس والبراس",
        categoryEn: "Copper & Brass",
        spec: "نقاء يصل إلى 99.9%",
        desc: "قضبان موصلة للتطبيقات الكهربائية وأعمال التشكيل الدقيق.",
        long: "قضبان نحاس إلكتروليتي عالي النقاء وقضبان براس للخراطة السريعة، مناسبة للتوصيلات الكهربائية ولوحات التوزيع وأعمال المخارط الدقيقة. متوفرة بمقاطع دائرية ومربعة ومسطحة.",
        items: [
          "C11000 — نحاس إلكتروليتي",
          "C36000 — براس للخراطة",
          "مقاطع دائرية · مربعة · مسطحة",
          "أقطار 5 – 150 مم",
          "طري · نصف صلب · صلب",
          "قضبان توزيع كهربائي",
        ],
        specs: [
          { k: "النقاء", v: "حتى 99.9% Cu" },
          { k: "المقاطع", v: "دائري · مربع · مسطح" },
          { k: "الأقطار", v: "5 مم – 150 مم" },
          { k: "الدرجات", v: "C11000 · C36000 برass" },
          { k: "الحالة", v: "طري · نصف صلب · صلب" },
        ],
        uses: ["قضبان التوزيع الكهربائي", "المحولات", "قطع الخراطة الدقيقة", "أنظمة التأريض"],
      },
      {
        slug: "structural-beams",
        name: "كمرات وقطاعات إنشائية",
        categoryEn: "Structural Steel",
        spec: "IPE · HEA · زوايا",
        desc: "قطاعات حديدية إنشائية للهناجر والمنشآت المعدنية الثقيلة.",
        long: "قطاعات إنشائية مدرفلة على الساخن تشمل كمرات IPE و HEA و HEB والزوايا والقنوات، مع خدمات القص والثقب والتجميع واللحام داخل المصنع قبل التسليم لموقع المشروع.",
        items: [
          "IPE · HEA · HEB · UPN",
          "زوايا وقنوات إنشائية",
          "S235 · S275 · S355",
          "جلفنة بالغمس الساخن",
          "قص · ثقب · تجميع · لحام",
          "دهان مقاوم للحريق",
        ],
        specs: [
          { k: "القطاعات", v: "IPE · HEA · HEB · UPN · زوايا" },
          { k: "الارتفاعات", v: "80 مم – 900 مم" },
          { k: "الدرجات", v: "S235 · S275 · S355" },
          { k: "الأطوال", v: "6 م – 12 م" },
          { k: "الحماية", v: "جلفنة بالغمس الساخن · دهان مقاوم للحريق" },
        ],
        uses: ["الهناجر الصناعية", "الجسور والمنصات", "أبراج الطاقة", "المباني متعددة الأدوار"],
      },
    ],
    servicesSection: {
      eyebrow: "الخدمات",
      title: "من السبيكة إلى الموقع",
      body: "نغطي دورة العمل كاملة: التوريد، التشكيل، المعالجة، والتسليم.",
    },
    services: [
      {
        n: "01",
        t: "قص بالليزر والبلازما",
        d: "قص دقيق بتفاوت ±0.1 مم على ماكينات CNC حديثة.",
      },
      { n: "02", t: "ثني وتشكيل", d: "مكابس هيدروليكية حتى 600 طن لتشكيل الألواح السميكة." },
      { n: "03", t: "لحام وتجميع", d: "فرق لحام معتمدة وفق مواصفات AWS و ASME." },
      { n: "04", t: "معالجة سطحية", d: "جلفنة، دهان إلكتروستاتيكي، وأنودة للألمنيوم." },
      { n: "05", t: "فحص الجودة", d: "اختبارات لا إتلافية وتقارير تحليل كيميائي لكل شحنة." },
      { n: "06", t: "لوجستيات التسليم", d: "أسطول نقل خاص يغطي دول مجلس التعاون." },
    ],
    about: {
      eyebrow: "من نحن",
      title: "مصنع مصري يصدّر إلى الخليج",
      body: "بدأت المؤسسة كمصنع صغير للحديد في مصر، واليوم تدير خطوط تصنيع متكاملة تخدم قطاعات الطاقة والإنشاءات والبنية التحتية في المملكة العربية السعودية ودول الخليج. نلتزم بالمواصفات السعودية والخليجية ونعمل مع مورّدين معتمدين عالمياً.",
      points: [
        "شهادات ISO 9001 و ISO 14001",
        "مختبر داخلي لتحليل تركيب السبائك",
        "مخزون دائم يغطي الطلبات العاجلة",
        "تصدير إلى المملكة العربية السعودية ودول الخليج",
      ],
    },
    contact: {
      eyebrow: "تواصل",
      title: "اطلب عرض سعر",
      body: "أرسل تفاصيل مشروعك وسيصلك عرض فني وسعري خلال 24 ساعة عمل.",
      name: "الاسم",
      company: "الجهة / الشركة",
      emailLabel: "البريد الإلكتروني",
      message: "تفاصيل الطلب",
      submit: "إرسال الطلب",
      sent: "تم استلام طلبك، سنعاود التواصل قريباً.",
      phoneLabel: "الهاتف",
      mailLabel: "البريد",
      addressLabel: "العنوان",
      address: "المصنع: مصر · التصدير إلى المملكة العربية السعودية ودول الخليج",
      phone: "+20 104 444 9783",
      email: "info@toptrustco.com",
      emailSecondary: "ahmed@toptrustco.com",
    },
    footerNote: "جميع الحقوق محفوظة",
    langToggle: "EN",
  },
  en: {
    dir: "ltr" as const,
    brand: "Top Trust Metal Products",
    brandShort: "Top Trust",
    tagline: "Built on trust",
    nav: {
      home: "Home",
      products: "Products",
      services: "Services",
      about: "About",
      contact: "Contact",
    },
    common: {
      viewDetails: "View details",
      backToProducts: "Back to products",
      specs: "Technical specifications",
      uses: "Applications",
      relatedProducts: "Other products",
      viewAll: "View all",
      requestProduct: "Request a quote for this product",
    },
    hero: {
      eyebrow: "Since 1998 · Factory in Egypt · Exporting to Saudi Arabia & the Gulf",
      title: "Metal built to last",
      titleAccent: "Built on trust",
      body: "An Egyptian factory specialising in the supply and fabrication of alloys and metal products, exporting to Saudi Arabia and the Gulf for construction, industrial and oil & gas projects — certified grades, precise tolerances, fast delivery.",
      cta: "Request a quote",
      cta2: "Browse products",
    },
    stats: [
      { value: "25+", label: "Years of work" },
      { value: "1,200+", label: "Projects delivered" },
      { value: "40+", label: "Alloys & grades" },
      { value: "24/7", label: "Logistics support" },
    ],
    productsSection: {
      eyebrow: "Products",
      title: "A complete portfolio for industry & construction",
      body: "Browse our main categories — from steel pipe and aluminium sheet to copper bar and structural sections.",
      note: "All products are available in multiple specifications and industrial quantities with quality certificates.",
    },
    products: [
      {
        slug: "steel-pipes",
        name: "Steel pipes & tubes",
        categoryEn: "Steel Pipes",
        spec: "Ø 6 mm – 1200 mm",
        desc: "Carbon and stainless pipe for industrial systems and transfer lines.",
        long: "Welded and seamless carbon and stainless steel pipe in a wide range of diameters and wall thicknesses, with in-house cutting, threading and external coating to project requirements. Every shipment ships with chemical analysis and pressure test certificates.",
        items: [
          "ASTM A106 / A53 — carbon steel",
          "SS 304 / SS 316 — stainless",
          "Hot dip galvanised",
          "Epoxy coated line pipe",
          "Cut & threaded to order",
          "Certified pressure testing",
        ],
        specs: [
          { k: "Diameter", v: "6 mm – 1200 mm" },
          { k: "Wall thickness", v: "1.5 mm – 40 mm" },
          { k: "Grades", v: "ASTM A106 / A53 / SS 304 / SS 316" },
          { k: "Lengths", v: "6 m · 12 m or cut to size" },
          { k: "Finish", v: "Black · galvanised · epoxy coated" },
        ],
        uses: ["Oil & gas lines", "Fire fighting & HVAC", "Structural frames", "Water networks"],
      },
      {
        slug: "aluminium-sheets",
        name: "Aluminium sheets & plates",
        categoryEn: "Aluminium Sheets",
        spec: "0.5 mm – 60 mm thick",
        desc: "Cold and hot rolled sheet with polished or textured finishes.",
        long: "Industrial grade aluminium sheet and plate, cold or hot rolled, available with mill, textured or anodised surfaces. We offer cut-to-size, bending and colour anodising services.",
        items: [
          "1050 · 3003 · 5083 · 6061",
          "Cold & hot rolled",
          "Mill · anodised · powder coated",
          "Cut to size ±0.1 mm",
          "CNC bending & forming",
          "Façade & industrial plate",
        ],
        specs: [
          { k: "Thickness", v: "0.5 mm – 60 mm" },
          { k: "Sizes", v: "1000×2000 · 1250×2500 · 1500×3000 mm" },
          { k: "Alloys", v: "1050 · 3003 · 5083 · 6061" },
          { k: "Finish", v: "Mill · anodised · powder coated" },
          { k: "Tolerance", v: "±0.1 mm" },
        ],
        uses: ["Building façades", "Trailer manufacturing", "Control panels", "Food equipment"],
      },
      {
        slug: "copper-rods",
        name: "Copper & brass rods",
        categoryEn: "Copper & Brass",
        spec: "Up to 99.9% purity",
        desc: "Conductive bar stock for electrical work and precision forming.",
        long: "High purity electrolytic copper bar and free-cutting brass rod for electrical connections, distribution boards and precision turning work. Available in round, square and flat sections.",
        items: [
          "C11000 — electrolytic copper",
          "C36000 — free-cutting brass",
          "Round · square · flat sections",
          "Diameters 5 – 150 mm",
          "Soft · half hard · hard",
          "Electrical busbar stock",
        ],
        specs: [
          { k: "Purity", v: "Up to 99.9% Cu" },
          { k: "Sections", v: "Round · square · flat" },
          { k: "Diameters", v: "5 mm – 150 mm" },
          { k: "Grades", v: "C11000 · C36000 brass" },
          { k: "Temper", v: "Soft · half hard · hard" },
        ],
        uses: ["Busbars", "Transformers", "Precision turned parts", "Earthing systems"],
      },
      {
        slug: "structural-beams",
        name: "Structural beams & profiles",
        categoryEn: "Structural Steel",
        spec: "IPE · HEA · angles",
        desc: "Structural sections for hangars and heavy steel structures.",
        long: "Hot rolled structural sections including IPE, HEA, HEB beams, angles and channels, with cutting, drilling, assembly and welding completed in our workshop before delivery to site.",
        items: [
          "IPE · HEA · HEB · UPN",
          "Angles & channels",
          "S235 · S275 · S355",
          "Hot dip galvanising",
          "Cut · drill · assemble · weld",
          "Intumescent fire paint",
        ],
        specs: [
          { k: "Sections", v: "IPE · HEA · HEB · UPN · angles" },
          { k: "Heights", v: "80 mm – 900 mm" },
          { k: "Grades", v: "S235 · S275 · S355" },
          { k: "Lengths", v: "6 m – 12 m" },
          { k: "Protection", v: "Hot dip galvanising · intumescent paint" },
        ],
        uses: ["Industrial hangars", "Bridges & platforms", "Power towers", "Multi-storey frames"],
      },
    ],
    servicesSection: {
      eyebrow: "Services",
      title: "From billet to site",
      body: "We cover the full cycle: supply, forming, treatment and delivery.",
    },
    services: [
      { n: "01", t: "Laser & plasma cutting", d: "±0.1 mm tolerance on modern CNC lines." },
      { n: "02", t: "Bending & forming", d: "Hydraulic presses up to 600 tons for heavy plate." },
      { n: "03", t: "Welding & assembly", d: "Certified crews working to AWS and ASME codes." },
      { n: "04", t: "Surface treatment", d: "Galvanising, powder coating and aluminium anodising." },
      { n: "05", t: "Quality inspection", d: "NDT testing and chemical analysis reports per batch." },
      { n: "06", t: "Delivery logistics", d: "Own fleet covering the entire GCC region." },
    ],
    about: {
      eyebrow: "About",
      title: "An Egyptian factory exporting to the Gulf",
      body: "We started as a small steel workshop in Egypt. Today we run integrated fabrication lines serving energy, construction and infrastructure clients across Saudi Arabia and the Gulf, working to Saudi and GCC specifications with globally approved suppliers.",
      points: [
        "ISO 9001 and ISO 14001 certified",
        "In-house lab for alloy composition analysis",
        "Standing stock for urgent orders",
        "Exporting to Saudi Arabia and the Gulf",
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Request a quote",
      body: "Send your project details and receive a technical and price offer within 24 working hours.",
      name: "Name",
      company: "Company",
      emailLabel: "Email",
      message: "Request details",
      submit: "Send request",
      sent: "Request received — we'll be in touch shortly.",
      phoneLabel: "Phone",
      mailLabel: "Email",
      addressLabel: "Address",
      address: "Factory: Egypt · Exporting to Saudi Arabia & the Gulf",
      phone: "+20 104 444 9783",
      email: "info@toptrustco.com",
      emailSecondary: "ahmed@toptrustco.com",
    },
    footerNote: "All rights reserved",
    langToggle: "ع",
  },
};
